### ISSUE TITLE
App icon in line with the GNOME HIG

### ISSUE THREAD

**Issue by kra-mo** [getseabird/seabird#19]
Hi!

The app seems to generally conform to the GNOME design guidelines, would you be interested in updating the app icon with one also in line with that?

If so, I would be willing to work on that.

**Comment by jgillich** [comment]
Hi, I really appreciate the offer! Unfortunately I just replaced our original icon yesterday and I think we'll stick with that one at least for a little while. I also worry that GNOME-style icons are a bit too generic for a cross platform app. Following GNOME design guidelines is more of a secondary goal for this project since it also runs on Mac and Windows. Among the cross-platform apps on my system, most use a round shape, so I think we can't really go wrong with that.
